version: '3.8'

services:
  # FastAPI Service
  fastapi:
    image: #https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-fastapi/tags
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - # FastAPI App Directory
    environment:
      - # Database URL
    depends_on:
      -

  # PostgreSQL Database Service
  db:
    image: # https://hub.docker.com/_/postgres/tags
    container_name: postgres_db
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: #testing
