name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Adjust branch name as needed

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11" # Adjust Python version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
          pip install pytest

      - name: Run Tests
        run: |
          pytest tests/

  # deploy:
  #   name: Deploy to Production
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main' # Deploy only on main branch

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2

  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: "3.11" # Adjust Python version as needed

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements/dev.txt

  #     - name: Deploy Application
  #       run: |
  #         # Replace this with your deployment script/command
  #         echo "Deploying FastAPI application to production server..."
